# -*- coding: utf-8 -*-
"""ml_helper_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-f7uBKlB152WzAbNIQG9_q9qJfNdAKKd
"""

import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow_hub as hub

import os
from os import walk

def get_file_names(dir_path):

  """
  It will return a list of file names from a directory, like getting class names from directory
  """
 
  return sorted(os.listdir(dir_path))